### ISSUE TITLE
Update all callbacks

### ISSUE THREAD

**Issue by darkwebdev** [eBay/ebayui-core-react#210]
According to #171 we should add callbacks with correct arguments where Marko version does it.
Components to update/check:
- [x] ebay-breadcrumbs
- [x] ebay-button
- [x] ebay-checkbox ([~issue in ebayUI marko~ fixed](https://github.com/eBay/ebayui-core/issues/1889))
- [x] ebay-confirm-dialog (on hold due to [issue in ebayUI marko](https://github.com/eBay/ebayui-core/issues/1887))
- [x] ebay-drawer-dialog (on hold due to [issue in ebayui marko](https://github.com/eBay/ebayui-core/issues/1890))
- [x] ebay-fake-menu ([~issue in ebayui marko~ fixed](https://github.com/eBay/ebayui-core/issues/1891))
- [x] ebay-fake-menu-button (on hold due to [issue in ebayui marko](https://github.com/eBay/ebayui-core/issues/1892))
- [x] ebay-icon-button
- [x] ebay-listbox-button
- [x] ebay-menu
- [x] ebay-menu-button
- [x] ebay-page-notice (ebayui marko [issue](https://github.com/eBay/ebayui-core/issues/1930))
- [x] ebay-pagination (ebayui marko [issue](https://github.com/eBay/ebayui-core/issues/1931))
- [x] ebay-radio (ebayui marko [issue](https://github.com/eBay/ebayui-core/issues/1932))
- [x] ebay-section-notice (ebayui marko [issue](https://github.com/eBay/ebayui-core/issues/1930))
- [x] ebay-select
- [x] ebay-split-button
- [x] ebay-star-rating-select
- [x] ebay-switch (ebayui marko [issue](https://github.com/eBay/ebayui-core/issues/1933))
- [x] ebay-tabs
- [x] ebay-textbox (ebayui marko [issue](https://github.com/eBay/ebayui-core/issues/1934))
- [x] ebay-video

**Comment by darkwebdev** [comment]
released in v5
